# Generated by Django 4.1.3 on 2022-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='.pictures/user_img/icon_user.png', upload_to='.pictures/user_img', verbose_name='User Photo'),
        ),
    ]
