# Generated by Django 4.1.3 on 2022-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='icon_user.png', upload_to='user_img', verbose_name='User Photo'),
        ),
    ]
