# Generated by Django 4.1.3 on 2022-11-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Мужской пол'), ('neutral', 'Гендерно-нейтральный'), ('other', 'Мужской пол')], default='oter', max_length=7, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif',
            field=models.BooleanField(default=True, help_text='Получать уведомления об интересных статьях?'),
        ),
    ]
