# Generated by Django 4.1.3 on 2022-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_gender_profile_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Мужской пол'), ('neutral', 'Гендерно-нейтральный'), ('other', 'Мужской пол')], default='other', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notif',
            field=models.BooleanField(default=True),
        ),
    ]
