# Generated by Django 4.1.3 on 2022-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_gender_alter_profile_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notif',
            new_name='notifications',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол'), ('neutral', 'Гендерно-нейтральный'), ('other', 'Другой пол')], default='other', max_length=7),
        ),
    ]
