# Generated by Django 4.1.4 on 2023-01-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_notif_profile_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Gender neutral'), ('other', 'Other gender')], default='other', max_length=7),
        ),
    ]
