# Generated by Django 4.1.5 on 2023-01-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Уникальное название урока')),
                ('title', models.CharField(max_length=100, verbose_name='Название урока')),
                ('desc', models.TextField(verbose_name='Описание урока')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('video', models.CharField(max_length=100, verbose_name='URL видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Какой курс')),
            ],
        ),
    ]
